export {
  OUTFIT_SLOT_DEFINITIONS,
  categoryMatchesOutfitSlot,
  formatRating,
  type LookupOption,
  type OutfitDetail,
  type OutfitItemDetail,
  type OutfitItemRow,
  type OutfitListRow,
  type OutfitLookups,
  type OutfitPickerItem,
  type OutfitRow,
  type OutfitSlot,
  type OutfitSlotDefinition,
  type OutfitSlotSelection,
  type SaveOutfitInput,
  type UpdateOutfitInput,
  type WearOutfitInput,
} from "@/types/wardrobe";
